# Generated by Django 5.1 on 2024-09-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('TCHR', 'Учитель'), ('CHLD', 'Ребенок'), ('PRNT', 'Родитель')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
