# Generated by Django 5.1 on 2024-09-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Учитель', 'Учитель'), ('Обучающийся', 'Обучающийся'), ('Родитель', 'Родитель')], max_length=50),
        ),
    ]
