# Generated by Django 5.1 on 2024-09-26 22:04

import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Учитель', 'Учитель'), ('Обучающийся', 'Обучающийся'), ('Родитель', 'Родитель'), ('Ребенок', 'Ребенок')], max_length=50),
        ),
    ]
