# Generated by Django 5.1 on 2024-09-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_course_course_price_course_course_price_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_duration',
            field=models.DurationField(null=True),
        ),
    ]
