# Generated by Django 5.1 on 2024-09-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_course_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_language',
            field=models.CharField(choices=[('KZ', 'Казахский'), ('RU', 'Русский'), ('EN', 'English')], default='KZ', max_length=33),
        ),
    ]
