# Generated by Django 5.1 on 2024-09-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_course_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_grade',
            field=models.CharField(choices=[('1', '1 Класс'), ('2', '2 Класс'), ('3', '3 Класс'), ('4', '4 Класс'), ('5', '5 Класс'), ('6', '6 Класс'), ('7', '7 Класс'), ('8', '8 Класс'), ('9', '9 Класс'), ('10', '10 Класс'), ('11', '11 Класс'), ('12', '12 Класс')], default='1', max_length=33, null=True),
        ),
    ]
