# Generated by Django 5.1 on 2024-09-24 22:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_course_course_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
