# Generated by Django 5.1 on 2024-09-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_course_course_content_course_course_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='category_description',
            field=models.CharField(default='Нужные навыки для школы подготовка', max_length=34),
        ),
    ]
