# Generated by Django 5.1 on 2024-09-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_article_author_article_article_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image_public',
            field=models.ImageField(default='', upload_to='blog/article_images/'),
            preserve_default=False,
        ),
    ]
