# Generated by Django 5.1 on 2024-09-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_deleted_article_modified_article_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_slug',
            field=models.SlugField(default=''),
        ),
    ]
