# Generated by Django 5.1 on 2024-09-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_article_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_small_description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
