# Generated by Django 5.1 on 2024-09-24 23:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
