# Generated by Django 5.1 on 2024-09-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_teacher_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
