# Generated by Django 5.1 on 2024-09-27 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_teacher_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
