# Generated by Django 5.1 on 2024-09-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ManyToManyField(to='eruditplatform.news')),
            ],
        ),
    ]
