# Generated by Django 5.1 on 2024-09-27 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0002_hotlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eruditplatform.news')),
            ],
        ),
        migrations.DeleteModel(
            name='HotLinks',
        ),
    ]
