# Generated by Django 5.1 on 2024-10-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentgrade',
            name='grade_range',
            field=models.IntegerField(default=100),
        ),
    ]
