# Generated by Django 5.1 on 2024-10-09 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0003_assignmentgrade_grade_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentgrade',
            old_name='grade_range',
            new_name='grade_max',
        ),
    ]
