# Generated by Django 5.1 on 2024-10-12 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0004_rename_grade_range_assignmentgrade_grade_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='attendance',
            field=models.ManyToManyField(blank=True, to='eruditplatform.groupattendance'),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='lesson_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
