# Generated by Django 5.1 on 2024-10-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0005_courselesson_attendance_courselesson_lesson_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupattendance',
            name='remark',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
