# Generated by Django 5.1 on 2024-09-27 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0006_timetable_timetableitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableitem',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='timetableitem',
            name='teacher',
        ),
        migrations.AddField(
            model_name='timetableitem',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='eruditplatform.coursegroups'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eruditplatform.coursegroups'),
        ),
    ]
