# Generated by Django 5.1 on 2024-09-27 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0007_remove_timetableitem_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='course',
            new_name='group',
        ),
    ]
