# Generated by Django 5.1 on 2024-10-13 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0007_remove_courseassignment_assignment_grades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselesson',
            name='assignments',
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='assignment_lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eruditplatform.courselesson'),
            preserve_default=False,
        ),
    ]
