# Generated by Django 5.1 on 2024-09-27 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0008_rename_course_timetable_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableitem',
            name='group',
        ),
    ]
