# Generated by Django 5.1 on 2024-09-27 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0010_timetable_created_timetable_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_slug', models.SlugField()),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eruditplatform.coursegroups')),
            ],
        ),
    ]
