# Generated by Django 5.1 on 2024-09-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0011_platformcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformcourse',
            name='course_slug',
            field=models.SlugField(null=True),
        ),
    ]
