# Generated by Django 5.1 on 2024-09-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0012_alter_platformcourse_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformcourse',
            name='course_slug',
            field=models.SlugField(blank=True, default='wef', unique=True),
            preserve_default=False,
        ),
    ]
