# Generated by Django 5.1 on 2024-09-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0013_alter_platformcourse_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformcourse',
            name='course_name',
            field=models.CharField(default='wefwef', max_length=255),
            preserve_default=False,
        ),
    ]
