# Generated by Django 5.1 on 2024-09-28 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0014_platformcourse_course_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlatformCourse',
        ),
    ]
