# Generated by Django 5.1 on 2024-09-28 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0015_delete_platformcourse'),
        ('school', '0011_course_course_type_alter_course_course_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegroups',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursegroups',
            name='teacher',
        ),
        migrations.CreateModel(
            name='PlatformCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.course')),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eruditplatform.coursegroups')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
