# Generated by Django 5.1 on 2024-10-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0016_remove_coursegroups_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='group',
        ),
        migrations.RemoveField(
            model_name='platformcourse',
            name='course_group',
        ),
        migrations.RemoveField(
            model_name='platformcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='platformcourse',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='timetableitem',
            name='time_table',
        ),
        migrations.DeleteModel(
            name='CourseGroups',
        ),
        migrations.DeleteModel(
            name='PlatformCourse',
        ),
        migrations.DeleteModel(
            name='TimeTable',
        ),
        migrations.DeleteModel(
            name='TimeTableItem',
        ),
    ]
