# Generated by Django 5.1 on 2024-10-08 18:31

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0021_groupattendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='GroupAssigment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_detail', ckeditor.fields.RichTextField()),
                ('assignment_attachments', models.ManyToManyField(to='eruditplatform.assignmentattachments')),
                ('group_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eruditplatform.groupcourse')),
            ],
        ),
        migrations.CreateModel(
            name='GroupGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('feedback', models.CharField(max_length=255)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eruditplatform.groupassigment')),
                ('group_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eruditplatform.groupcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
