# Generated by Django 5.1 on 2024-10-08 18:35

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0022_assignmentattachments_groupassigment_groupgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_detail', ckeditor.fields.RichTextField()),
                ('group_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eruditplatform.groupcourse')),
                ('lesson_attachments', models.ManyToManyField(to='eruditplatform.assignmentattachments')),
            ],
        ),
    ]
