# Generated by Django 5.1 on 2024-10-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0023_grouplesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupassigment',
            name='group_course',
        ),
        migrations.RemoveField(
            model_name='groupattendance',
            name='group_course',
        ),
        migrations.RemoveField(
            model_name='groupgrade',
            name='group_course',
        ),
        migrations.AddField(
            model_name='groupassigment',
            name='assignment_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupcourse',
            name='group_assignments',
            field=models.ManyToManyField(to='eruditplatform.groupassigment'),
        ),
        migrations.AddField(
            model_name='groupcourse',
            name='group_attendence',
            field=models.ManyToManyField(to='eruditplatform.groupattendance'),
        ),
        migrations.AddField(
            model_name='groupcourse',
            name='group_grade',
            field=models.ManyToManyField(to='eruditplatform.groupgrade'),
        ),
        migrations.AddField(
            model_name='groupcourse',
            name='group_lesson',
            field=models.ManyToManyField(to='eruditplatform.grouplesson'),
        ),
        migrations.AddField(
            model_name='grouplesson',
            name='assignments',
            field=models.ManyToManyField(to='eruditplatform.groupassigment'),
        ),
    ]
