# Generated by Django 5.1 on 2024-10-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0024_remove_groupassigment_group_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=10),
        ),
    ]
