# Generated by Django 5.1 on 2024-10-08 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0025_alter_groupattendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcourse',
            name='group_assignments',
        ),
    ]
