# Generated by Django 5.1 on 2024-10-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0027_grouplesson_lesson_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouplesson',
            name='group_course',
        ),
    ]
