# Generated by Django 5.1 on 2024-10-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0028_remove_grouplesson_group_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplesson',
            name='assignments',
            field=models.ManyToManyField(blank=True, to='eruditplatform.groupassigment'),
        ),
        migrations.AlterField(
            model_name='grouplesson',
            name='lesson_attachments',
            field=models.ManyToManyField(blank=True, to='eruditplatform.assignmentattachments'),
        ),
    ]
