# Generated by Django 5.1 on 2024-10-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0029_alter_grouplesson_assignments_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupAssigment',
            new_name='GroupAssignment',
        ),
    ]
