# Generated by Django 5.1 on 2024-10-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0030_rename_groupassigment_groupassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcourse',
            name='group_attendence',
            field=models.ManyToManyField(blank=True, to='eruditplatform.groupattendance'),
        ),
        migrations.AlterField(
            model_name='groupcourse',
            name='group_grade',
            field=models.ManyToManyField(blank=True, to='eruditplatform.groupgrade'),
        ),
        migrations.AlterField(
            model_name='groupcourse',
            name='group_lesson',
            field=models.ManyToManyField(blank=True, to='eruditplatform.grouplesson'),
        ),
    ]
