# Generated by Django 5.1 on 2024-10-08 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0031_alter_groupcourse_group_attendence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupassignment',
            name='assignment_due',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupassignment',
            name='assignment_opened',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
