# Generated by Django 5.1 on 2024-10-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0032_groupassignment_assignment_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupassignment',
            name='assignemnts_note',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
