# Generated by Django 5.1 on 2024-10-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0033_groupassignment_assignemnts_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupassignment',
            old_name='assignemnts_note',
            new_name='assignemnt_note',
        ),
    ]
