# Generated by Django 5.1 on 2024-10-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eruditplatform', '0035_alter_groupassignment_assignment_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentattachments',
            name='file',
            field=models.FileField(upload_to='attachments'),
        ),
    ]
